name: couchbase_lite_dart
version: 0.5.0-nullsafety.3
description: Dart implementation of Couchbase Lite is an embedded, NoSQL JSON Document Style database.
homepage: https://github.com/Rudiksz/couchbase_lite_dart
repository: https://github.com/Rudiksz/couchbase_lite_dart
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  ffi: ^1.0.0
  uuid: ^3.0.1
  meta: ^1.2.3
  path: ^1.7.0
  cblite_flutter_libs:
    path: './flutter_libs'
dev_dependencies:
  test: ^1.5.3
  pedantic: ^1.0.0
  ffigen: ^2.4.1